# name= input("Enter your name: ")
# print("your name is "+name)
# age= input("Enter your age: ")
# print("your name is "+age)

num1= int(input("Enter your first number: "))
print("your first number is "+str(num1))
num2= int(input("Enter your second number: "))
print("your second number is "+str(num2))
print("total is: "+str(num1+num2))
print("total is in folat: "+str(float(num1+num2)))